// UPSC Exam Centers — Official list from UPSC CSE notification
export const UPSC_CENTERS: { code: string; city: string; state: string }[] = [
  { code: 'AGR', city: 'Agra',               state: 'Uttar Pradesh' },
  { code: 'AHM', city: 'Ahmedabad',          state: 'Gujarat' },
  { code: 'AIZ', city: 'Aizawl',             state: 'Mizoram' },
  { code: 'ALG', city: 'Aligarh',            state: 'Uttar Pradesh' },
  { code: 'ALD', city: 'Prayagraj',          state: 'Uttar Pradesh' },
  { code: 'AUR', city: 'Aurangabad',         state: 'Maharashtra' },
  { code: 'BRL', city: 'Bareilly',           state: 'Uttar Pradesh' },
  { code: 'BHO', city: 'Bhopal',             state: 'Madhya Pradesh' },
  { code: 'CHD', city: 'Chandigarh',         state: 'Punjab/Haryana' },
  { code: 'CHE', city: 'Chennai',            state: 'Tamil Nadu' },
  { code: 'CUT', city: 'Cuttack',            state: 'Odisha' },
  { code: 'DDN', city: 'Dehradun',           state: 'Uttarakhand' },
  { code: 'DEL', city: 'Delhi',              state: 'Delhi' },
  { code: 'DHR', city: 'Dharwad',            state: 'Karnataka' },
  { code: 'DIS', city: 'Dispur (Guwahati)',  state: 'Assam' },
  { code: 'GTK', city: 'Gangtok',            state: 'Sikkim' },
  { code: 'HYD', city: 'Hyderabad',          state: 'Telangana' },
  { code: 'IMP', city: 'Imphal',             state: 'Manipur' },
  { code: 'ITA', city: 'Itanagar',           state: 'Arunachal Pradesh' },
  { code: 'JAI', city: 'Jaipur',             state: 'Rajasthan' },
  { code: 'JAM', city: 'Jammu',              state: 'J&K' },
  { code: 'JDH', city: 'Jodhpur',            state: 'Rajasthan' },
  { code: 'JOR', city: 'Jorhat',             state: 'Assam' },
  { code: 'KOC', city: 'Kochi',              state: 'Kerala' },
  { code: 'KOH', city: 'Kohima',             state: 'Nagaland' },
  { code: 'KOL', city: 'Kolkata',            state: 'West Bengal' },
  { code: 'KZH', city: 'Kozhikode',          state: 'Kerala' },
  { code: 'LKW', city: 'Lucknow',            state: 'Uttar Pradesh' },
  { code: 'MAD', city: 'Madurai',            state: 'Tamil Nadu' },
  { code: 'MUM', city: 'Mumbai',             state: 'Maharashtra' },
  { code: 'NAG', city: 'Nagpur',             state: 'Maharashtra' },
  { code: 'PAN', city: 'Panaji (Goa)',       state: 'Goa' },
  { code: 'PAT', city: 'Patna',              state: 'Bihar' },
  { code: 'PBL', city: 'Port Blair',         state: 'A&N Islands' },
  { code: 'PNE', city: 'Pune',               state: 'Maharashtra' },
  { code: 'RAI', city: 'Raipur',             state: 'Chhattisgarh' },
  { code: 'RAN', city: 'Ranchi',             state: 'Jharkhand' },
  { code: 'SAM', city: 'Sambalpur',          state: 'Odisha' },
  { code: 'SHL', city: 'Shillong',           state: 'Meghalaya' },
  { code: 'SHM', city: 'Shimla',             state: 'Himachal Pradesh' },
  { code: 'SRN', city: 'Srinagar',           state: 'J&K' },
  { code: 'TRV', city: 'Thiruvananthapuram', state: 'Kerala' },
  { code: 'TRP', city: 'Tirupati',           state: 'Andhra Pradesh' },
  { code: 'UDA', city: 'Udaipur',            state: 'Rajasthan' },
  { code: 'VZG', city: 'Vishakhapatnam',     state: 'Andhra Pradesh' },
];

export const MAX_CENTERS = 4; // UPSC allows max 4 center preferences
